### ISSUE TITLE
Regarding missing part of en_zh_st train set of CoVoST2 in HypoTranslate

### ISSUE THREAD

**Issue by SWivid** [YUCHEN005/GenTranslate#3]
from huggingface it seems only have
[train_mustc_en_zh_st_large.pt](https://huggingface.co/datasets/PeacefulData/HypoTranslate/blob/main/en-x/train/train_mustc_en_zh_st_large.pt)
[train_fleurs_en_zh_st_large.pt](https://huggingface.co/datasets/PeacefulData/HypoTranslate/blob/main/en-x/train/train_fleurs_en_zh_st_large.pt)

While train_covost2_en_zh_st_large.pt and other language pair .pts non-existed

Curious about your excellent work, need this trying out intergrating performance.o(*￣▽￣*)ブ

**Comment by YUCHEN005** [comment]
Hi, we apologize for unable to release your mentioned data files due to copyright at this time, we hope to release it months later. if you are hurry, please use our scripts [here](https://drive.google.com/drive/folders/1ljchsSlxqegHZNZhiPm50RiBvSUl9vwu?usp=sharing) to generate such data.

1. download official [seamless_m4t](https://github.com/facebookresearch/seamless_communication/tree/main), install required packages, and replace the file `src/seamless_communication/inference/translator.py` with ours.

2. enter our `gen_seamless_covost2_st.py`, specify the arguments `split`, `langpair`, `modelsize` (see default values for reference), then specify the path of your covost2 source data ([tutorial](https://github.com/facebookresearch/covost?tab=readme-ov-file#covost-2)), and the path of generated data (.pt file). then run this script.

3. tokenize the text in generate data: enter our `transfer_seamless.py`, and specify the arguments with default values for reference, llama2 path, and data path. finally run this script.

Hope it helps, thanks.

**Comment by SWivid** [comment]
Thanks a lot. Best Regards.
